### ISSUE TITLE
在某次bing更新后似乎失效了

### ISSUE THREAD

**Issue by DarknessChaser** [levinit/bing-image-download-button#3]
现在无法获得正确的dom了，导致后面解析流程出错。

**Comment by levinit** [comment]
> 现在无法获得正确的dom了，导致后面解析流程出错。

什么浏览器  更新了safar的tampermonkey确实不行了    ff正常

**Comment by DarknessChaser** [comment]
> > 现在无法获得正确的dom了，导致后面解析流程出错。
> 
> 什么浏览器 更新了safar的tampermonkey确实不行了 ff正常

Firefox 打开开发者工具->网络，勾选清除缓存，刷新页面

**Comment by DarknessChaser** [comment]
应该是dom结构变化导致的

**Comment by levinit** [comment]
> 应该是dom结构变化导致的

刚试了下 firefox 97 ，greasemonkey ，正常

**Comment by DarknessChaser** [comment]
> > 应该是dom结构变化导致的
> 
> 刚试了下 firefox 97 ，greasemonkey ，正常

刚刚试了下我这里也是好的，打扰了。 屋子里的那台上的FF有问题，我回去排查一下。
